include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - tools/bricks/**/__brick__/**

  errors:
    avoid_field_initializers_in_const_classes: ignore
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
