name: investlink
description: "InvestLink Project"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easy_dialogs: ^3.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.2.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  logging: ^1.2.0
  meta: ^1.15.0
  nested: ^1.0.0
  path: ^1.9.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.4.1
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: SFProDisplay
      fonts:
        # - asset: assets/fonts/sf-pro-display/SFPRODISPLAYExtraBold.OTF
        #   weight: 700
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 600
        # - asset: assets/fonts/sf-pro-display/SFPRODISPLAYSEMIBOLD.OTF
        #   weight: 500
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 400
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
          weight: 300
        # - asset: assets/fonts/sf-pro-display/SFPRODISPLAYLight.OTF
        #   weight: 200
        # - asset: assets/fonts/sf-pro-display/SFPRODISPLAYExtraLight.OTF
        #   weight: 100
